# Generated by Django 5.0.2 on 2024-04-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_listing_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
